/******************************************************************************/
/*           Generated by IBExpert 2025.6.24.1 2026-01-24 10:19:20            */
/******************************************************************************/

/******************************************************************************/
/*        Following SET SQL DIALECT is just for the Database Comparer         */
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/*                             Stored procedures                              */
/******************************************************************************/



SET TERM ^ ;

CREATE OR ALTER PROCEDURE PROC_RETURN_STRING (
    KOMUNIKAT_WE VARCHAR(200))
RETURNS (
    WYJSCIE VARCHAR(200),
    DATA_WY TIMESTAMP)
AS
BEGIN
  SUSPEND;
END^





SET TERM ; ^



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/



CREATE TABLE TABELA_INSERTOW (
    INDEKS      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    DATA_WPISU  TIMESTAMP DEFAULT 'now' NOT NULL,
    KOMUNIKAT   VARCHAR(500)
);



/******************************************************************************/
/*                                Primary keys                                */
/******************************************************************************/

ALTER TABLE TABELA_INSERTOW ADD CONSTRAINT PK_TABELA_INSERTOW PRIMARY KEY (INDEKS);


/******************************************************************************/
/*                             Stored procedures                              */
/******************************************************************************/



SET TERM ^ ;

CREATE OR ALTER PROCEDURE PROC_RETURN_STRING (
    KOMUNIKAT_WE VARCHAR(200))
RETURNS (
    WYJSCIE VARCHAR(200),
    DATA_WY TIMESTAMP)
AS
begin
  data_wy = 'now';
  wyjscie = komunikat_we;

  suspend;
end^




SET TERM ; ^

